name: laux
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32467645895667374
title: laux
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#1caaaa'
    - '#2f2f2f'
    - '#cccccc'
  brandStrength: 1
  lightness: 0.8723555481992662
  saturation: 0.6879771477542818
  rhythmicContrast: 0.5
purpose: []
